# .github/workflows/deploy.yml

name: Deploy React App to S3 and CloudFront

on:
  push:
    branches:
      - main # Trigger on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VITE_GOOGLE_AUTH_CLIENT_ID: ${{ secrets.VITE_GOOGLE_AUTH_CLIENT_ID }}
      VITE_BACKEND_BASE_URL: ${{ secrets.VITE_BACKEND_BASE_URL }}
      VITE_STRIPE_PAYMENT_LINK: ${{ secrets.VITE_STRIPE_PAYMENT_LINK }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Or your preferred Node.js version
          # Add this line to automatically set up pnpm
          cache: 'pnpm' # Cache pnpm modules for faster subsequent builds

      - name: Install pnpm
        run: npm install -g pnpm@latest-10 # Install pnpm globally

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile # Use pnpm install. --no-frozen-lockfile can be useful if your lockfile might not be perfectly up-to-date in CI, otherwise remove it for stricter builds.

      - name: Build React app
        run: pnpm build # Or pnpm run build, depending on your package.json script

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }} # Corrected from your previous snippet, should be AWS_SECRET_ACCESS_KEY
          aws-region: ap-southeast-2 # Replace with your S3 bucket's region

      - name: Deploy to S3
        run: aws s3 sync ./build s3://upsiftai.com --delete # Replace your-bucket-name

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id E1W8Y3P5JX5T5S --paths "/*"
